version: '3'

services:
  db:
    image         : mariadb:10.4.29
    container_name: cf_mariadb
    restart       : unless-stopped
    ports:
      - "3306:3306/tcp"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    command: mysqld --sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max_allowed_packet=16M
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin status"]

  web:
    build          : .
    container_name: cf_apache
    restart       : unless-stopped
    ports:
      - "80:80"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -s http://localhost/v9/rest/readiness"]
    environment:
      UPLOAD_LIMIT: 256M
